import {
  ADDRESS_VERSION,
  COIN_NAME,
  COIN_SYMBOL,
  DERIVATION_PATH,
  EDX_DECIMALS,
  EDX_UNIT,
  PHASE_1_MAX_HEIGHT,
  PHASE_2_DIVISOR,
  PHASE_2_MAX_HEIGHT,
  TARGET_BLOCK_SECONDS,
  PHASE_3_REWARD,
  parseEdxAmount,
  phaseForHeight,
} from "@edgex/shared";

export {
  COIN_NAME,
  COIN_SYMBOL as COIN_TICKER,
  EDX_DECIMALS as COIN_DECIMALS,
  ADDRESS_VERSION,
  DERIVATION_PATH as DEFAULT_DERIVATION_PATH,
  PHASE_1_MAX_HEIGHT as PHASE1_LAST_HEIGHT,
  PHASE_2_MAX_HEIGHT as PHASE2_LAST_HEIGHT,
  PHASE_2_DIVISOR as PHASE2_DIVISOR,
  TARGET_BLOCK_SECONDS as BLOCK_INTERVAL_SECONDS,
  phaseForHeight,
};

export type { RewardPhase as MiningPhase } from "@edgex/shared";

export const COIN_UNIT = EDX_UNIT;
export const MAX_SUPPLY_EDX = 2_100_000_000n;
export const MAX_SUPPLY = MAX_SUPPLY_EDX * COIN_UNIT;
export const BIP44_COIN_TYPE = 778;
export const MINING_MATURITY_CONFIRMATIONS = 6;

export const PHASE1_REWARD = 400n * EDX_UNIT;
export const PHASE3_REWARD = PHASE_3_REWARD;
